### ISSUE TITLE
sal should depend on cmsis-core

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/sal#23]
sal includes cmsis.h in https://github.com/ARMmbed/sal/blob/master/mbed-net-socket-abstract/socket_api.h#L95

It should therefore depend on cmsis-core.

This issue is related to https://github.com/ARMmbed/target-st-stm32f429i-disco/issues/16 

This really fixes the compile error of the 6lowpan example for F429.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-834

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-990
